/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2024-12-26 18:10:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<style>\r\n");
      out.write("  @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Comforter&family=Gasoek+One&family=Oi&family=Sigmar&display=swap');\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Anton+SC&display=swap');\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Grand+Hotel&display=swap');\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap');\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Belanosima&family=Rubik+Vinyl&display=swap');\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Grand+Hotel&display=swap');\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap');\r\n");
      out.write("\r\n");
      out.write("        html\r\n");
      out.write("        {\r\n");
      out.write("            scroll-behavior: smooth;\r\n");
      out.write("        }\r\n");
      out.write("        body\r\n");
      out.write("        {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            font-family: \"Poppins\", sans-serif;\r\n");
      out.write("            background-image: linear-gradient(to right, #6a11cb 0%, #2575fc 100%);\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .spectacledcoder-navbar\r\n");
      out.write("        {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            z-index: 100;\r\n");
      out.write("            background-image: linear-gradient(to right, #6a11cb 0%, #2575fc 100%);\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("        }\r\n");
      out.write("        .spectacledcoder-navbar .brand\r\n");
      out.write("        {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            width: fit-content;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        .spectacledcoder-navbar .brand h1\r\n");
      out.write("        {\r\n");
      out.write("            font-family: \"Comforter\", cursive;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            color: rgb(255, 255, 255);\r\n");
      out.write("        }\r\n");
      out.write("        .spectacledcoder-navbar ul\r\n");
      out.write("        {\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-left: 0px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        .spectacledcoder-navbar ul li\r\n");
      out.write("        {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-left: 0px;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("        }\r\n");
      out.write("        .rect\r\n");
      out.write("        {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-left: 0px;\r\n");
      out.write("            width: 0%;\r\n");
      out.write("            height: 2px;\r\n");
      out.write("            background-color: rgb(255, 255, 255);\r\n");
      out.write("        }\r\n");
      out.write("        .spectacledcoder-navbar ul li:hover .rect\r\n");
      out.write("        {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            transition: all 0.5s;\r\n");
      out.write("        }\r\n");
      out.write("        .spectacledcoder-navbar ul li a\r\n");
      out.write("        {\r\n");
      out.write("            font-family: \"Poppins\", sans-serif;\r\n");
      out.write("            font-size: smaller;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: rgb(255, 255, 255);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .spectacledcoder-navbar .navbar-toggler\r\n");
      out.write("        {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            height: 40%;\r\n");
      out.write("            display: none;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.5s;\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        .spectacledcoder-navbar .navbar-toggler .line1, .spectacledcoder-navbar .navbar-toggler .line2\r\n");
      out.write("        {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 1px;\r\n");
      out.write("            background-color: rgb(255, 255, 255);\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        .overlay-dropdown\r\n");
      out.write("        {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        .overlay-dropdown ul li\r\n");
      out.write("        {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("        #intro-div, #about-div, #services-div, #careers-div, #contact-div\r\n");
      out.write("        {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("        }\r\n");
      out.write("        #intro-div h2, #about-div h2, #services-div h2, #careers-div h2, #contact-div h2\r\n");
      out.write("        {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            font-size: 7vw;\r\n");
      out.write("            color: rgb(255, 255, 255);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        @media only screen and (max-width: 1000px)\r\n");
      out.write("        {\r\n");
      out.write("            .spectacledcoder-navbar ul\r\n");
      out.write("            {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("            .spectacledcoder-navbar .navbar-toggler\r\n");
      out.write("            {\r\n");
      out.write("                display: flex;\r\n");
      out.write("            }\r\n");
      out.write("            .overlay-dropdown\r\n");
      out.write("        {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            display: none;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            background-color: rgb(255, 255, 255);\r\n");
      out.write("        }\r\n");
      out.write("        .overlay-dropdown .brand\r\n");
      out.write("        {\r\n");
      out.write("           margin: auto;\r\n");
      out.write("           height: 60px;\r\n");
      out.write("           margin-left: 20px;\r\n");
      out.write("           margin-top: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        .overlay-dropdown .brand h1\r\n");
      out.write("        {\r\n");
      out.write("            font-family: \"Comforter\", cursive;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .overlay-dropdown ul\r\n");
      out.write("        {\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            height: 60%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            margin-left: -16px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .overlay-dropdown ul li\r\n");
      out.write("        {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        .overlay-dropdown ul li a\r\n");
      out.write("        {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: black;\r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .disclaimer\r\n");
      out.write("        { \r\n");
      out.write("            margin: auto; \r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            width: fit-content;\r\n");
      out.write("            color: rgb(255, 255, 255);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-family: 'Belanosima', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        .disclaimer a\r\n");
      out.write("        {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-family: \"Kaushan Script\", cursive;\r\n");
      out.write("            font-weight: 900;\r\n");
      out.write("        }\r\n");
      out.write("        .disclaimer a:hover\r\n");
      out.write("        {\r\n");
      out.write("            text-decoration: overline;\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"overlay-dropdown\" id=\"overlay\">\r\n");
      out.write("        <div class=\"brand\">\r\n");
      out.write("            <h1>SpectacledCoder</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#intro-div\" onclick=\"navigation()\">Home</a></li>\r\n");
      out.write("            <li><a href=\"#about-div\" onclick=\"navigation()\">About</a></li>\r\n");
      out.write("            <li><a href=\"#services-div\" onclick=\"navigation()\">Services</a></li>\r\n");
      out.write("            <li><a href=\"#careers-div\" onclick=\"navigation()\">Careers</a></li>\r\n");
      out.write("            <li><a href=\"#contact-div\" onclick=\"navigation()\">Contact</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"spectacledcoder-navbar\">\r\n");
      out.write("        <div class=\"brand\">\r\n");
      out.write("            <h1>SpectacledCoder</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#intro-div\">Home</a><div class=\"rect\"></div></li>\r\n");
      out.write("            <li><a href=\"#about-div\">About</a><div class=\"rect\"></div></li>\r\n");
      out.write("            <li><a href=\"#services-div\">Services</a><div class=\"rect\"></div></li>\r\n");
      out.write("            <li><a href=\"#careers-div\">Careers</a><div class=\"rect\"></div></li>\r\n");
      out.write("            <li><a href=\"#contact-div\">Contact</a><div class=\"rect\"></div></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-toggler\" id=\"toggler\" onclick=\"mobilenav()\">\r\n");
      out.write("            <div class=\"line1\" id=\"ln1\"></div>\r\n");
      out.write("            <div class=\"line2\" id=\"ln2\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"intro-div\"><h2>HOME</h2></div>\r\n");
      out.write("    <div id=\"about-div\"><h2>ABOUT</h2></div>\r\n");
      out.write("    <div id=\"services-div\"><h2>SERVICES</h2></div>\r\n");
      out.write("    <div id=\"careers-div\"><h2>CAREERS</h2></div>\r\n");
      out.write("    <div id=\"contact-div\"><h2>CONTACT</h2></div>\r\n");
      out.write("    <p class=\"disclaimer\">Designed & Created by SpectacledCoder</p>\r\n");
      out.write("    <script>\r\n");
      out.write("    var toggler = document.getElementById(\"toggler\");\r\n");
      out.write("    var overlay = document.getElementById(\"overlay\");\r\n");
      out.write("    var ln1 = document.getElementById(\"ln1\");\r\n");
      out.write("    var ln2 = document.getElementById(\"ln2\");\r\n");
      out.write("    var toggleflag = 0;\r\n");
      out.write("\r\n");
      out.write("    var intro = document.getElementById('intro-div');\r\n");
      out.write("    var about = document.getElementById('about-div');\r\n");
      out.write("    var services = document.getElementById('services-div');\r\n");
      out.write("    var careers = document.getElementById('careers-div');\r\n");
      out.write("    var contact = document.getElementById('contact-div');\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    function mobilenav()\r\n");
      out.write("    {\r\n");
      out.write("        if (toggleflag == 0)\r\n");
      out.write("        {\r\n");
      out.write("            overlay.style.display = \"flex\";\r\n");
      out.write("            ln1.style.transform = \"rotate(50deg)\";\r\n");
      out.write("            ln2.style.transform = \"rotate(-50deg)\";\r\n");
      out.write("            toggler.style.height = \"1px\";\r\n");
      out.write("            intro.style.display = 'none';\r\n");
      out.write("            about.style.display = 'none';\r\n");
      out.write("            services.style.display = 'none';\r\n");
      out.write("           \r\n");
      out.write("            careers.style.display = 'none';\r\n");
      out.write("            contact.style.display = 'none';\r\n");
      out.write("            toggleflag = 1;\r\n");
      out.write("        }\r\n");
      out.write("        else\r\n");
      out.write("        {\r\n");
      out.write("            overlay.style.display = \"none\";\r\n");
      out.write("            ln1.style.transform = \"rotate(0deg)\";\r\n");
      out.write("            ln2.style.transform = \"rotate(0deg)\";\r\n");
      out.write("            toggler.style.height = \"40%\";\r\n");
      out.write("            intro.style.display = 'flex';\r\n");
      out.write("            about.style.display = 'flex';\r\n");
      out.write("            services.style.display = 'flex';\r\n");
      out.write("          \r\n");
      out.write("            careers.style.display = 'flex';\r\n");
      out.write("            contact.style.display = 'flex';\r\n");
      out.write("            toggleflag = 0;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function navigation()\r\n");
      out.write("    {\r\n");
      out.write("        overlay.style.display = \"none\";\r\n");
      out.write("        ln1.style.transform = \"rotate(0deg)\";\r\n");
      out.write("        ln2.style.transform = \"rotate(0deg)\";\r\n");
      out.write("        toggler.style.height = \"40%\";\r\n");
      out.write("        intro.style.display = 'flex';\r\n");
      out.write("        about.style.display = 'flex';\r\n");
      out.write("        services.style.display = 'flex';\r\n");
      out.write("       \r\n");
      out.write("        careers.style.display = 'flex';\r\n");
      out.write("        contact.style.display = 'flex';\r\n");
      out.write("        toggleflag = 0;\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
